<?php

return [
    'home' => [
        ['key' => 'hero_image', 'type' => 'image', 'label_en' => 'Hero Background Image', 'label_ar' => 'صورة خلفية البطل', 'default_path' => 'images/hero.jpg'],
        ['key' => 'hero_title', 'type' => 'text', 'label_en' => 'Hero Title', 'label_ar' => 'عنوان البطل', 'default_en' => 'BEYOND ORDINARY', 'default_ar' => 'تجاوز المعتاد'],
        ['key' => 'hero_subtitle', 'type' => 'text', 'label_en' => 'Hero Subtitle', 'label_ar' => 'العنوان الفرعي', 'default_en' => 'FOR MEN WHO REFUSE TO BE AVERAGE', 'default_ar' => 'لرجال يرفضون أن يكونوا عاديين'],
        ['key' => 'philosophy_label', 'type' => 'text', 'label_en' => 'Philosophy Eyebrow Label', 'label_ar' => 'تسمية قسم الفلسفة', 'default_en' => 'OUR PHILOSOPHY', 'default_ar' => 'فلسفتنا'],
        ['key' => 'philosophy_title_before', 'type' => 'text', 'label_en' => 'Philosophy Title — Text Before Highlight', 'label_ar' => 'عنوان الفلسفة — النص قبل الكلمة المميزة', 'default_en' => 'ULTRA IS NOT JUST CLOTHING AND ACCESSORIES. IT IS A', 'default_ar' => 'ULTRA ليست مجرد ملابس وإكسسوارات. إنها'],
        ['key' => 'philosophy_title_highlight', 'type' => 'text', 'label_en' => 'Philosophy Title — Highlighted Word', 'label_ar' => 'عنوان الفلسفة — الكلمة المميزة', 'default_en' => 'MODERN HEIRLOOM', 'default_ar' => 'قطعة خالدة عصرية'],
        ['key' => 'philosophy_title_after', 'type' => 'text', 'label_en' => 'Philosophy Title — Text After Highlight', 'label_ar' => 'عنوان الفلسفة — النص بعد الكلمة المميزة', 'default_en' => '.', 'default_ar' => '.'],
        ['key' => 'philosophy_body', 'type' => 'textarea', 'label_en' => 'Philosophy Body', 'label_ar' => 'نص الفلسفة', 'default_en' => 'Precision engineering meets heritage aesthetics. We design for the individual who demands excellence in every stitch, every link, and every moment of their life.', 'default_ar' => 'الهندسة الدقيقة تلتقي بجمال التراث. نصمم لمن يطلب التميز في كل غرزة، كل حلقة، وكل لحظة من حياته.'],
        ['key' => 'newsletter_title', 'type' => 'text', 'label_en' => 'Newsletter Title', 'label_ar' => 'عنوان النشرة البريدية', 'default_en' => 'Join The Elite', 'default_ar' => 'انضم إلى النخبة'],
        ['key' => 'newsletter_body', 'type' => 'textarea', 'label_en' => 'Newsletter Body', 'label_ar' => 'نص النشرة البريدية', 'default_en' => 'Subscribe to receive early access to new collections and exclusive lifestyle content. No noise. Just the elite.', 'default_ar' => 'اشترك لتحصل على وصول مبكر للتشكيلات الجديدة ومحتوى حصري. بدون ضجيج. فقط النخبة.'],
    ],

    'about' => [
        ['key' => 'hero_image', 'type' => 'image', 'label_en' => 'Hero Background Image', 'label_ar' => 'صورة خلفية البطل', 'default_path' => 'images/about-hero.jpg'],
        ['key' => 'hero_title_before', 'type' => 'text', 'label_en' => 'Hero Title — Text Before Highlight', 'label_ar' => 'عنوان البطل — النص قبل الكلمة المميزة', 'default_en' => 'FOR MEN WHO REFUSE TO BE', 'default_ar' => 'لمن يرفض أن يكون'],
        ['key' => 'hero_title_highlight', 'type' => 'text', 'label_en' => 'Hero Title — Highlighted Word', 'label_ar' => 'عنوان البطل — الكلمة المميزة', 'default_en' => 'AVERAGE', 'default_ar' => 'عادياً'],
        ['key' => 'hero_title_after', 'type' => 'text', 'label_en' => 'Hero Title — Text After Highlight', 'label_ar' => 'عنوان البطل — النص بعد الكلمة المميزة', 'default_en' => '.', 'default_ar' => '.'],
        ['key' => 'pillars_title', 'type' => 'text', 'label_en' => 'Pillars Section Title', 'label_ar' => 'عنوان قسم الأعمدة', 'default_en' => 'The Pillars of Excellence', 'default_ar' => 'أعمدة التميز'],
        ['key' => 'pillars_subtitle', 'type' => 'textarea', 'label_en' => 'Pillars Section Subtitle', 'label_ar' => 'العنوان الفرعي لقسم الأعمدة', 'default_en' => 'Three core ideologies that define every piece we produce and every partnership we forge.', 'default_ar' => 'ثلاث مبادئ أساسية تحدد كل قطعة ننتجها وكل شراكة نبنيها.'],
        ['key' => 'quote', 'type' => 'textarea', 'label_en' => 'Quote', 'label_ar' => 'الاقتباس', 'default_en' => 'The man who is satisfied with being average has already lost his greatest asset: his potential.', 'default_ar' => 'الرجل الذي يرضى بأن يكون عادياً، خسر بالفعل أعظم ما يملك: إمكانياته.'],
        ['key' => 'quote_author', 'type' => 'text', 'label_en' => 'Quote Author', 'label_ar' => 'قائل الاقتباس', 'default_en' => '— ULTRA FOUNDRY', 'default_ar' => '— ألترا فاوندري'],
        ['key' => 'cta_title', 'type' => 'text', 'label_en' => 'Newsletter CTA Title', 'label_ar' => 'عنوان دعوة الاشتراك', 'default_en' => 'Elevate Your Existence.', 'default_ar' => 'ارفع مستوى وجودك.'],
        ['key' => 'cta_body', 'type' => 'textarea', 'label_en' => 'Newsletter CTA Body', 'label_ar' => 'نص دعوة الاشتراك', 'default_en' => 'Join our private mailing list for early access to the Archive collections and invitations to exclusive member-only events. No noise. Only value.', 'default_ar' => 'انضم إلى قائمتنا البريدية الخاصة للحصول على وصول مبكر لتشكيلات الأرشيف ودعوات لفعاليات حصرية للأعضاء فقط. بلا ضجيج. قيمة فقط.'],
        ['key' => 'philosophy_image', 'type' => 'image', 'label_en' => 'Philosophy Image', 'label_ar' => 'صورة الفلسفة', 'default_path' => 'images/about-craftsmanship.jpg'],
        ['key' => 'philosophy_headline_before', 'type' => 'text', 'label_en' => 'Philosophy Headline — Text Before Highlight', 'label_ar' => 'عنوان الفلسفة — النص قبل الكلمة المميزة', 'default_en' => 'ULTRA is not just clothing. It is a', 'default_ar' => 'ألترا ليست مجرد ملابس. إنها'],
        ['key' => 'philosophy_headline_highlight', 'type' => 'text', 'label_en' => 'Philosophy Headline — Highlighted Phrase', 'label_ar' => 'عنوان الفلسفة — العبارة المميزة', 'default_en' => 'disciplined lifestyle', 'default_ar' => 'نمط حياة منضبط'],
        ['key' => 'philosophy_headline_after', 'type' => 'text', 'label_en' => 'Philosophy Headline — Text After Highlight', 'label_ar' => 'عنوان الفلسفة — النص بعد الكلمة المميزة', 'default_en' => '.', 'default_ar' => '.'],
        ['key' => 'philosophy_description', 'type' => 'textarea', 'label_en' => 'Philosophy Description', 'label_ar' => 'وصف الفلسفة', 'default_en' => 'We believe that how a man presents himself to the world is the ultimate reflection of his internal standard. ULTRA was born from the desire to equip the modern pioneer with more than just aesthetic excellence. We provide the uniform for those who lead, those who create, and those who demand precision in every facet of their existence.', 'default_ar' => 'نؤمن بأن طريقة تقديم الرجل لنفسه أمام العالم هي أصدق انعكاس لمعاييره الداخلية. وُلدت ألترا من الرغبة في تجهيز الريادي العصري بأكثر من مجرد تميز جمالي. نقدم الزي المناسب لمن يقودون، ومن يبدعون، ومن يطلبون الدقة في كل جانب من وجودهم.'],
        ['key' => 'lifestyle_image', 'type' => 'image', 'label_en' => 'Lifestyle Image', 'label_ar' => 'صورة نمط الحياة', 'default_path' => 'images/about-lifestyle.jpg'],
        ['key' => 'new_standard', 'type' => 'text', 'label_en' => 'Quote Section Heading', 'label_ar' => 'عنوان قسم الاقتباس', 'default_en' => 'A New Standard', 'default_ar' => 'معيار جديد'],
        ['key' => 'pillar_1_title', 'type' => 'text', 'label_en' => 'Pillar 1 Title', 'label_ar' => 'عنوان العمود الأول', 'default_en' => 'Precision', 'default_ar' => 'الدقة'],
        ['key' => 'pillar_1_desc', 'type' => 'textarea', 'label_en' => 'Pillar 1 Description', 'label_ar' => 'وصف العمود الأول', 'default_en' => 'Every millimeter is considered. Our silhouettes are engineered to command presence, utilizing geometric cutting techniques that mirror modern architecture.', 'default_ar' => 'كل مليمتر له حسابه. تصاميمنا مصممة لتفرض حضورها، باستخدام تقنيات قص هندسية تحاكي العمارة الحديثة.'],
        ['key' => 'pillar_2_title', 'type' => 'text', 'label_en' => 'Pillar 2 Title', 'label_ar' => 'عنوان العمود الثاني', 'default_en' => 'Materiality', 'default_ar' => 'جودة الخامات'],
        ['key' => 'pillar_2_desc', 'type' => 'textarea', 'label_en' => 'Pillar 2 Description', 'label_ar' => 'وصف العمود الثاني', 'default_en' => 'We source only the rarest fibers and highest-grade hides. If it doesn\'t improve with age, it doesn\'t belong in the ULTRA collection.', 'default_ar' => 'نستورد فقط أندر الألياف وأرقى أنواع الجلود. إن لم تتحسن مع الزمن، فلا مكان لها في تشكيلة ألترا.'],
        ['key' => 'pillar_3_title', 'type' => 'text', 'label_en' => 'Pillar 3 Title', 'label_ar' => 'عنوان العمود الثالث', 'default_en' => 'Exclusivity', 'default_ar' => 'التفرّد'],
        ['key' => 'pillar_3_desc', 'type' => 'textarea', 'label_en' => 'Pillar 3 Description', 'label_ar' => 'وصف العمود الثالث', 'default_en' => 'ULTRA is not for the masses. We produce in limited runs to ensure that when you wear ULTRA, you are part of a select few who value rarity over reach.', 'default_ar' => 'ألترا ليست للجميع. نُصنّع بكميات محدودة لنضمن أنك عندما ترتدي ألترا، تكون من القلة المميزة التي تقدّر الندرة على الانتشار.'],
    ],

    'contact' => [
        ['key' => 'showroom_image', 'type' => 'image', 'label_en' => 'Showroom Image', 'label_ar' => 'صورة صالة العرض', 'default_path' => 'images/contact-showroom.jpg'],
        ['key' => 'craftsman_image', 'type' => 'image', 'label_en' => 'Craftsmanship Image', 'label_ar' => 'صورة الحرفية', 'default_path' => 'images/contact-craftsman.jpg'],
        ['key' => 'gentleman_image', 'type' => 'image', 'label_en' => 'Lifestyle Image', 'label_ar' => 'صورة نمط الحياة', 'default_path' => 'images/contact-gentleman.jpg'],
        ['key' => 'get_in_touch', 'type' => 'text', 'label_en' => 'Hero Title', 'label_ar' => 'عنوان البطل', 'default_en' => 'Get In Touch', 'default_ar' => 'تواصل معنا'],
        ['key' => 'hero_body', 'type' => 'textarea', 'label_en' => 'Hero Body', 'label_ar' => 'نص البطل', 'default_en' => 'Whether you are seeking a bespoke commission or have an inquiry about our seasonal archives, our concierge is at your disposal.', 'default_ar' => 'سواء كنت تبحث عن طلب خاص أو لديك استفسار عن تشكيلاتنا الموسمية، خدمة عملائنا في خدمتك.'],
        ['key' => 'showroom_address', 'type' => 'text', 'label_en' => 'Showroom Address', 'label_ar' => 'عنوان صالة العرض', 'default_en' => '482 Lexington Avenue', 'default_ar' => '482 Lexington Avenue'],
        ['key' => 'showroom_city', 'type' => 'text', 'label_en' => 'Showroom City', 'label_ar' => 'مدينة صالة العرض', 'default_en' => 'Manhattan, New York 10017', 'default_ar' => 'مانهاتن، نيويورك 10017'],
        ['key' => 'showroom_country', 'type' => 'text', 'label_en' => 'Showroom Country', 'label_ar' => 'دولة صالة العرض', 'default_en' => 'United States', 'default_ar' => 'الولايات المتحدة الأمريكية'],
        ['key' => 'contact_email', 'type' => 'text', 'label_en' => 'Contact Email', 'label_ar' => 'البريد الإلكتروني', 'default_en' => 'concierge@ultra.luxury', 'default_ar' => 'concierge@ultra.luxury'],
        ['key' => 'contact_phone', 'type' => 'text', 'label_en' => 'Contact Phone', 'label_ar' => 'رقم الهاتف', 'default_en' => '+1 (212) 555-0198', 'default_ar' => '+1 (212) 555-0198'],
        ['key' => 'hours', 'type' => 'textarea', 'label_en' => 'Hours (one line each)', 'label_ar' => 'ساعات العمل (سطر لكل فترة)', 'default_en' => "Monday — Friday: 10am — 7pm\nSaturday: 11am — 5pm\nSunday: By Appointment Only", 'default_ar' => "الإثنين — الجمعة: 10 صباحاً — 7 مساءً\nالسبت: 11 صباحاً — 5 مساءً\nالأحد: بموعد مسبق فقط"],
    ],

    'footer' => [
        ['key' => 'footer_tagline', 'type' => 'textarea', 'label_en' => 'Footer Tagline', 'label_ar' => 'شعار الفوتر', 'default_en' => 'Crafting modern heirlooms for the discerning individual. Precision, heritage, and contemporary luxury defined.', 'default_ar' => 'نصنع قطعاً خالدة للفرد المميز. الدقة والتراث والرفاهية المعاصرة في تعريف واحد.'],
        ['key' => 'footer_rights', 'type' => 'text', 'label_en' => 'Copyright Line', 'label_ar' => 'سطر حقوق النشر', 'default_en' => 'ALL RIGHTS RESERVED.', 'default_ar' => 'جميع الحقوق محفوظة.'],
        ['key' => 'social_instagram', 'type' => 'url', 'label_en' => 'Instagram Link', 'label_ar' => 'رابط إنستغرام', 'default' => ''],
        ['key' => 'social_twitter', 'type' => 'url', 'label_en' => 'Twitter / X Link', 'label_ar' => 'رابط تويتر / X', 'default' => ''],
        ['key' => 'social_linkedin', 'type' => 'url', 'label_en' => 'LinkedIn Link', 'label_ar' => 'رابط لينكدإن', 'default' => ''],
        ['key' => 'social_facebook', 'type' => 'url', 'label_en' => 'Facebook Link', 'label_ar' => 'رابط فيسبوك', 'default' => ''],
        ['key' => 'social_tiktok', 'type' => 'url', 'label_en' => 'TikTok Link', 'label_ar' => 'رابط تيك توك', 'default' => ''],
    ],
];
